name: Build and Deploy

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'
      
      - name: Install dependencies
        run: pip install -r requirements.txt
      
      - name: Run static code analysis
        run: pylint toDo.py
        
      - name: Check code style
        run: flake8 toDo.py
      
      - name: Run tests
        run: python -m unittest discover

      - name: Build
        run: python toDo.py --file todo_list.txt add --title "Clean house" --description "Floor, windows, dish"
      
      
      - name: Archive artifact
        uses: actions/upload-artifact@v2
        with:
          name: todo-list-artifact
          path: todo_list.txt
      
      
      - name: Deploy artifact
        uses: actions/upload-artifact@v2
        with:
          name: todo-list-deploy
          path: todo_list.txt
